import cv2
img = cv2.imread('pic/Girl.bmp', 0)
ret, dst_OSTU = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
dst1 = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 7, 5)
dst2 = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 21, 5)
cv2.imshow("img", img)
cv2.imshow("OTSU", dst_OSTU)
cv2.imshow("adaptive7", dst1)
cv2.imshow("adaptive21", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()
