import cv2
import numpy as np
img = cv2.imread('pic/flower02.jpg')
cv2.imshow('img', img)
lower = np.array([20, 60, 60])
upper = np.array([30, 255, 255])
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
result = cv2.inRange(hsv, lower, upper)
kernel = np.ones((5, 5), np.uint8)
result = cv2.morphologyEx(result, cv2.MORPH_OPEN, kernel)
cv2.imshow('open', result)
contours, hiera = cv2.findContours(result, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
mask = np.zeros_like(img)
cv2.drawContours(mask, contours, -1, (255, 255, 255), -1)
cv2.imshow('mask', mask)
dst = cv2.bitwise_and(img, mask)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

